### ISSUE TITLE
Error require node-geoip package after migrating to yarn 2

### ISSUE THREAD

**Issue by roiePowerInbox** [geoip-lite/node-geoip#215]
After migrating a monorepo project to yarn 2 (using new Workspace feature)
`const geoip = require("geoip-lite");` throws an error.

> /.yarn/cache/geoip-lite-npm-1.4.2-b73c3a4713-1a820eac0d.zip/node_modules/geoip-lite/lib/geoip.js:337
throw err;
^
RangeError [ERR_OUT_OF_RANGE]: The value of "fd" is out of range. It must be >= 0 && <= 2147483647. Received -2147483645
at Object.fstatSync (fs.js:995:3)
at preload (/.yarn/cache/geoip-lite-npm-1.4.2-b73c3a4713-1a820eac0d.zip/node_modules/geoip-lite/lib/geoip.js:321:17)
at Object.<anonymous> (/.yarn/cache/geoip-lite-npm-1.4.2-b73c3a4713-1a820eac0d.zip/node_modules/geoip-lite/lib/geoip.js:533:1)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load (internal/modules/cjs/loader.js:879:32)
at Function.external_module_.Module._load (/.pnp.js:10709:14)
at Module.require (internal/modules/cjs/loader.js:903:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/apps/user/user-api/server/services/sendUserProfile/index.js:4:15) {
code: 'ERR_OUT_OF_RANGE'
}

Using `"geoip-lite": "^1.4.0"`

**Comment by bjshort** [comment]
Same issue here. It seems this package is not compatible with [Yarn PnP](https://next.yarnpkg.com/features/pnp).

**Comment by bluesmoon** [comment]
I'd appreciate a patch if you can figure out how to fix it. I don't even know what Yarn is.

**Comment by bjshort** [comment]
Actually, this is actually a caused by an issue with Yarn itself, which is solved by https://github.com/yarnpkg/berry/pull/2320.

Currently, this change is not included in the latest release of Yarn (v2.4.0), so to get this change you'll need to run `yarn set version from sources` if you are using Yarn2.
