### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS after automatic update

### ISSUE THREAD

**Issue by smein** [geoip-lite/node-geoip#240]
After using `updatedb` today, our node processes that are set to `geoip.startWatchingDataUpdate()` started throwing this error:

```
2022-06-08 22:38:05.858: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
2022-06-08 22:38:05.858:     at new NodeError (node:internal/errors:371:5)
2022-06-08 22:38:05.858:     at boundsError (node:internal/buffer:84:11)
2022-06-08 22:38:05.858:     at Buffer.readUInt32BE (node:internal/buffer:309:5)
2022-06-08 22:38:05.858:     at readip (.../node_modules/geoip-lite/lib/geoip.js:158:19)
2022-06-08 22:38:05.858:     at lookup6 (.../node_modules/geoip-lite/lib/geoip.js:164:18)
2022-06-08 22:38:05.858:     at Object.lookup (.../node_modules/geoip-lite/lib/geoip.js:467:12)
2022-06-08 22:38:05.858:     at isBlocked (.../node-ipgeoblock/index.js:70:21)
2022-06-08 22:38:05.858:     at .../node-ipgeoblock/index.js:102:22
```

It persists for all queries (or maybe only ipv6 queries?), but is fixed after a restart of the node processes

**Comment by bluesmoon** [comment]
which version of geoip?

**Comment by smein** [comment]
geoip-lite version 1.4.5
